In [1]:
import pandas as pd
ds_jobs = pd.read_csv("../data/processed/ds_jobs.csv")
skill_df = pd.read_csv("../data/processed/skill_demand.csv")

print("Datasets loaded successfully!")
print("DS Jobs:", ds_jobs.shape)
print("Skill Demand:", skill_df.shape)

Datasets loaded successfully!
DS Jobs: (1307, 31)
Skill Demand: (22, 2)

In [2]:
career_paths = {
    "Data Analyst": ["SQL", "Excel", "Power BI", "Tableau", "Statistics"],
    "Data Scientist": ["Python", "SQL", "Machine Learning", "Statistics", "Pandas"],
    "Data Engineer": ["SQL", "Python", "AWS", "Spark", "ETL"],
    "Machine Learning Engineer": ["Python", "Machine Learning", "Deep Learning", "TensorFlow", "PyTorch"],
    "BI Analyst": ["SQL", "Power BI", "Tableau", "Excel", "Statistics"]
}

In [3]:
my_skills = [
    "Python",
    "SQL",
    "Machine Learning"
]

In [4]:
recommendations = []

for role, required_skills in career_paths.items():
    matched = []
    missing = []

    for skill in required_skills:
        if skill in my_skills:
            matched.append(skill)
        else:
            missing.append(skill)

    score = (len(matched) / len(required_skills)) * 100

    recommendations.append({
        "Role": role,
        "Match Score": round(score, 2),
        "Matched Skills": matched,
        "Missing Skills": missing
    })

recommendation_df = pd.DataFrame(recommendations)

recommendation_df

,Role,Match Score,Matched Skills,Missing Skills
0,Data Analyst,20.0,[SQL],"[Excel, Power BI, Tableau, Statistics]"
1,Data Scientist,60.0,"[Python, SQL, Machine Learning]","[Statistics, Pandas]"
2,Data Engineer,40.0,"[SQL, Python]","[AWS, Spark, ETL]"
3,Machine Learning Engineer,40.0,"[Python, Machine Learning]","[Deep Learning, TensorFlow, PyTorch]"
4,BI Analyst,20.0,[SQL],"[Power BI, Tableau, Excel, Statistics]"

In [5]:
recommendation_df = recommendation_df.sort_values(
    by="Match Score",
    ascending=False
)

recommendation_df

,Role,Match Score,Matched Skills,Missing Skills
1,Data Scientist,60.0,"[Python, SQL, Machine Learning]","[Statistics, Pandas]"
2,Data Engineer,40.0,"[SQL, Python]","[AWS, Spark, ETL]"
3,Machine Learning Engineer,40.0,"[Python, Machine Learning]","[Deep Learning, TensorFlow, PyTorch]"
0,Data Analyst,20.0,[SQL],"[Excel, Power BI, Tableau, Statistics]"
4,BI Analyst,20.0,[SQL],"[Power BI, Tableau, Excel, Statistics]"

In [6]:
best_role = recommendation_df.iloc[0]

print("===== SkillScope Career Recommendation =====")
print("Recommended Career:", best_role["Role"])
print(f"Match Score: {best_role['Match Score']}/100")

print("\nSkills You Already Have:")
for skill in best_role["Matched Skills"]:
    print("✅", skill)

print("\nSkills You Need to Learn:")
for skill in best_role["Missing Skills"]:
    print("❌", skill)

===== SkillScope Career Recommendation =====
Recommended Career: Data Scientist
Match Score: 60.0/100

Skills You Already Have:
✅ Python
✅ SQL
✅ Machine Learning

Skills You Need to Learn:
❌ Statistics
❌ Pandas